server:
  port: 8040
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anian1989/SpringCloudConfigProperties/     # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:   junshuaizhang@163.com                                          # git仓库的账号
          password:   vvoszjs19890205                                        # git仓库的密码